### Makefile -- Word Generator

# Author: Michael Grünewald
# Date: Tue Jan 14 08:00:06 CET 2014

# Gasoline (https://github.com/michipili/gasoline)
# This file is part of Gasoline
#
# Copyright © 2014 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt

PROGRAM=		wordcount

SRCS+=			count.ml
SRCS+=			display.ml
SRCS+=			wordcount.ml

USES+=			odoc

.include "ocaml.prog.mk"

### End of file `Makefile'
