### Makefile -- Application patterns

# Author: Michael Grünewald
# Date: Sat Dec 28 13:07:19 CET 2013

# Gasoline (https://github.com/michipili/gasoline)
# This file is part of Gasoline
#
# Copyright © 2013 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt

LIBRARY=		gasoline_application

SRCS=			gasoline_Unicode.ml
SRCS+=			gasoline_SysExits.ml

SRCS+=			gasoline_Generic_Definition.ml
SRCS+=			gasoline_Generic_Asset.ml
SRCS+=			gasoline_Generic_Application.ml

SRCS+=			gasoline_Plain_Definition.ml
SRCS+=			gasoline_Plain_Application.ml
SRCS+=			gasoline_Plain_Filter.ml

.include "ocaml.lib.mk"

### End of file `Makefile'
