### Makefile -- Application patterns

# Author: Michael Grünewald
# Date: Sat Dec 28 13:07:19 CET 2013

# Gasoline (https://github.com/michipili/gasoline)
# This file is part of Gasoline
#
# Copyright © 2013 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt

SRCS+=	unicode.ml
SRCS+=	sysExits.ml
SRCS+=	getopt.ml

SRCS+=	cType.ml
SRCS+=	cConfiguration.ml
SRCS+=	cMessage.ml
SRCS+=	cApplication.ml

SRCS+=	configuration_parser.mll
SRCS+=	configuration.ml

SRCS+=	generic_type.ml
SRCS+=	generic_message.ml
SRCS+=	generic_diagnostic.ml
SRCS+=	generic_application.ml

.include "gasoline.library.mk"

### End of file `Makefile'
