### Makefile -- Author kit

# Author: Michael Grünewald
# Date: Tue Jun  3 11:44:56 CEST 2014

# Gasoline (https://github.com/michipili/gasoline)
# This file is part of Gasoline
#
# Copyright © 2014 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt

TESTS=		test_sgml_simple_1
TESTS+=		test_sgml_simple_2
TESTS+=		test_sgml_simple_3
TESTS+=		test_html_simple_1
TESTS+=		test_html_simple_2
TESTS+=		test_html_simple_3

TESTENV=	LANG=en_US.UTF-8

.include "gasoline.trip-trap.mk"

### End of file `Makefile'
