### Makefile -- Test suite

# Author: Michael Grünewald
# Date: Tue Nov  5 22:54:56 CET 2013

# GIT-Toolkit (https://github.com/michipili/gasoline)
# This file is part of Gasoline
#
# Copyright © 2013 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt

SUBDIR+=	unit-testing
SUBDIR+=	trip-trap

install build:
	${NOP}

.include "gasoline.subdir.mk"

### End of file `Makefile'
