### Makefile -- Document writers

# Author: Michael Grünewald
# Date: Sat 21 Feb 2009 09:19:53 CET

# Gasoline (https://github.com/michipili/gasoline)
# This file is part of Gasoline
#
# Copyright © 2009–2014 Michael Grünewald
#
# This file must be used under the terms of the CeCILL-B.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution. The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt

SRCS = wSGML.ml
SRCS+= wHTML.ml
SRCS+= loremIpsum.ml

.include "gasoline.library.mk"

### End of file `Makefile'
